name: tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'mixxxdj/demucs' || github.event_name == 'workflow_dispatch' }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - uses: actions/cache@v4
      with:
        path: env
        key: tests-${{ hashFiles('**/requirements.txt') }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        python3 -m venv env
        . env/bin/activate
        python -m pip install --upgrade pip
        pip install '.[dev]'

    # FIXME: missing dependencies!
    # - name: Run separation test
    #   run: |
    #     . env/bin/activate
    #     make test_eval

    - name: Run pytest
      run: |
        . env/bin/activate
        pytest ./tests/
